import Head from 'next/head'
import { Props } from './interfaces'
import styles from './layout.module.sass'

const Layout = ({ children, title }: Props) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <div className={styles.title}>HACKER NEWS</div>
        <div>{children}</div>
      </div>
    </div>
  )
}

export default Layout
