export const listTypes = {
    GET: 'GET',
    GET_SUCCESS: 'GET_SUCCESS',
    GET_ERROR: 'GET_ERROR',
    GET_LIST_FAV: 'GET_LIST_FAV',
    GET_LIST_FAV_SUCCESS: 'GET_LIST_FAV_SUCCESS',
    GET_LIST_FAV_ERROR: 'GET_LIST_FAV_ERROR',
}